typography_spectrum: 0.02873765816912055
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1155168884433806
  lightness: 0.7045879699289799
  saturation: 0.7235930801834911
  rhythmicContrast: 0.3023532582446933
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3234783022198826
analytics:
  google: null
  facebook: null
  twitter: null
name: Amr Shafik
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
